# Request
float64 v                       # 最大速度, 最大速度，此版本无效，默认写入0.0。  [rad/s]
float64 acc                     # 最大加速度，此版本无效，默认写入0.0。 [rad/s^2]
float64 time                    # 执行时间, 间隔点之间的运行时间        [s]
float64 lookahead_time          # 前瞻时间, 此版本无效, 默认写入0.2     [s]
int32 gain                      # 位置跟踪参数，该参数越大，跟踪越慢，超调量越小，范围[100, 1000]
int8 arm_type                   # 机器人身体部位。 仅当使用V1版本且全身控制时有用,用来指定当前要控制的目标部位,可以通过8421码进行叠加
---

# Response
bool success
string message





# -----------------------------------------------------------------
# arm_type 8421码定义:
# 左臂为1,右臂为2,颈部为4,半身腰为8,轮臂腰上下平移为16
# 
# 
# 不同机型可以使用的部位:
# - 半身带腰：左臂为1，右臂为2，颈部为4， 半身腰为8。
# - 半身不带腰：左臂为1，右臂为2，颈部为4。
# - 轮臂：左臂为1，右臂为2，颈部为4，轮臂腰为8，轮臂腰上下平移为16。
# -----------------------------------------------------------------