# Request
geometry_msgs/PoseArray poses           # 单手目标序列（每个Pose包含位置和姿态）
float64[] time_points                   # 每个点的绝对时间（或每段时长，需约定）
float64 max_period                      # 最大等待周期
float64 weight                          # 每段权重
string which_arm                        # 指定左右手 "left", "right"

---
# Response
bool success