<?xml version="1.0"?>
<package format="2">
  <name>mpc_hardware_interface</name>
  <version>0.0.1</version>
  <description>MPC hardware interface message and service definitions.</description>

  <maintainer email="user@example.com">naviai</maintainer>
  <license>Proprietary</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>message_generation</build_depend>
  <build_depend>std_msgs</build_depend>

  <exec_depend>message_runtime</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <export/>
</package>
